name: Continuous Integration

on:
  push:
    branches:
      - main
      - develop
      - "hotfix/*"
      - "release/*"
      - "feature/*"
  pull_request:
    branches:
      - develop
      - main
      - "release/*"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: ok-nick/setup-aftman@v0.3.0
        name: Install aftman
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Lint
        run: |
          selene ./src

  style:
    name: Styling
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: StyLua
        uses: JohnnyMorganz/stylua-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check ./src
