name: Deploy Roblox Place

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Deployment environment"
        required: true
        type: environment

      placeId:
        description: "Place ID"
        required: true

      deployRef:
        description: "Git ref to deploy (defaults to the ref that triggered this workflow)"
        required: false

      projectFileName:
        description: "Project file name"
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.deployRef || github.sha }}
          submodules: recursive

      - uses: ok-nick/setup-aftman@v0.3.0
        name: Install aftman
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check environment is configured to deploy to Roblox
        run: |
          set -e

          if ! ${{ fromJSON(vars.DEPLOY_TO_ROBLOX || 'false') }}; then
            echo "Environment has not been configured to deploy to Roblox"
            exit 1
          fi

          echo "Proceeding with attempt to deploy to Roblox"

      - name: Validate place belongs to universe
        run: |
          set -e

          rbxcloud place get \
            -p ${{ github.event.inputs.placeId }} \
            -u ${{ vars.UNIVERSE_ID }} \
            -a ${{ secrets.PUBLISH_API_KEY }} > /dev/null

      - name: Load place map
        id: placemap
        run: |
          echo "MAP=$(cat place-map.json | jq -c .)" >> $GITHUB_OUTPUT

      - name: Resolve folder alias
        id: alias
        run: |
          map='${{ steps.placemap.outputs.MAP }}'
          projectFile="${{ github.event.inputs.projectFileName }}"
          alias=$(echo "$map" | jq -r --arg p "$projectFile" '.[$p]')
          if [ "$alias" = "null" ]; then
            echo "Project file not found in place-map.json"
            exit 1
          fi
          echo "ALIAS=$alias" >> $GITHUB_OUTPUT

      - name: List mapped directories
        run: |
          ls -la internal-packages
          ls -la internal-packages/Fusion/src

          ls -la place-packages/${{ steps.alias.outputs.ALIAS }}/client/Packages
          ls -la place-packages/${{ steps.alias.outputs.ALIAS }}/server/Packages
          ls -la place-packages/${{ steps.alias.outputs.ALIAS }}/shared/Packages
          find Packages -maxdepth 3 -type f | sed -n '1,200p'

      - name: Install Wally (client-only env)
        run: cd place-packages/${{ steps.alias.outputs.ALIAS }}/client && wally install

      - name: Install Wally (server-only env)
        run: cd place-packages/${{ steps.alias.outputs.ALIAS }}/server && wally install

      - name: Install Wally (shared env)
        run: cd place-packages/${{ steps.alias.outputs.ALIAS }}/shared && wally install

      - name: Ensure Packages folders + init.meta.json exist
        run: |
          BASE="place-packages/${{ steps.alias.outputs.ALIAS }}"

          for scope in client server shared; do
            PKG_DIR="$BASE/$scope/Packages"

            mkdir -p "$PKG_DIR"

            if [ -z "$(ls -A "$PKG_DIR")" ]; then
              echo "Packages empty for $scope, creating init.meta.json"

              echo '{"ignoreUnknownInstances": true, "className": "Folder", "properties": {}}' > "$PKG_DIR/init.meta.json"
            fi
          done

      - name: Build place with Rojo
        run: rojo build ${{ inputs.projectFileName }} -o BuildArtifact.rbxl

      - name: Deploy to selected environment experience
        run: |
          rbxcloud experience publish \
            -f BuildArtifact.rbxl \
            -i ${{ github.event.inputs.placeId }} \
            -u ${{ vars.UNIVERSE_ID }} \
            -t published \
            -a ${{ secrets.PUBLISH_API_KEY }}
